name: ManhuntPlugin
version: '${version}'
main: seml.manhunt.Manhunt
api-version: '1.21'
description: 5인 맨헌트 게임을 위한 플러그인
author: Twinkleping

commands:
  manhunt:
    description: 맨헌트 게임 관리 명령어
    usage: /manhunt <start|stop|reset|setrunner> [player]
    permission: manhunt.admin
    permission-message: "이 명령어를 사용할 권한이 없습니다."
  tracker:
    description: 헌터용 나침반 명령어
    usage: /tracker
    # permission 제거 - 게임 내에서 헌터 여부로 체크

permissions:
  manhunt.admin:
    description: 맨헌트 관리자 권한
    default: op
  manhunt.hunter:
    description: 헌터 권한
    default: false
  manhunt.runner:
    description: 러너 권한
    default: false
